import {
  Building2,
  PersonStanding,
  Phone,
  MapPin,
  User,
  Mail,
  Lock,
  Database,
  Calendar,
  Percent,
  FileBadge2,
  Receipt,
} from "lucide-react";
export const tenantFormFields = (formData: any) => [
  {
    id: 1,
    name: "name",
    type: "text",
    value: formData.name,
    label: "Company Name",
    placeHolder: "UnitedContracting",
    icon:  Building2 ,
  },
  {
    id: 2,
    name: "industry",
    type: "text",
    value: formData.industry,
    label: "Industry",
    placeHolder: "Construction",
    icon:  Building2 ,
  },
  {
    id: 3,
    name: "phone",
    type: "text",
    value: formData.phone,
    label: "Phone Number",
    placeHolder: "+1 234 567 890",
    icon:  Phone ,
  },
  {
    id: 4,
    name: "maxEmployees",
    type: "number",
    value: formData.maxEmployees,
    label: "Number of Employees",
    placeHolder: "Enter employee count",
    icon:  PersonStanding ,
  },
  {
    id: 5,
    name: "address",
    type: "text",
    value: formData.address,
    label: "Address",
    placeHolder: "",
    icon:  MapPin ,
  },
  {
    id: 6,
    name: "adminName",
    type: "text",
    value: formData.adminName,
    label: "Admin Name",
    placeHolder: "John Doe",
    icon:  User ,
  },
  {
    id: 7,
    name: "adminEmail",
    type: "email",
    value: formData.adminEmail,
    label: "Admin Email",
    placeHolder: "john.doe@company.com",
    icon:  Mail ,
  },
  {
    id: 8,
    name: "adminPassword",
    type: "password",
    value: formData.adminPassword,
    label: "Admin Password",
    placeHolder: "",
    icon:  Lock ,
  },
  {
    id: 9,
    name: "kvkNumber",
    type: "text",
    value: formData.kvkNumber,
    label: "KVK Number",
    placeHolder: "",
    icon:  FileBadge2 ,
  },
  {
    id: 10,
    name: "btwNumber",
    type: "text",
    value: formData.btwNumber,
    label: "BTW Number",
    placeHolder: "",
    icon:  Receipt ,
  },
  {
    id: 11,
    name: "databaseName",
    type: "text",
    value: formData.databaseName,
    label: "Database Name",
    placeHolder: "",
    icon:  Database ,
  },
  {
    id: 12,
    name: "subscriptionStartDate",
    type: "date",
    value: formData.subscriptionStartDate,
    label: "Subscription Start Date",
    placeHolder: "",
    icon:  Calendar ,
  },
  {
    id: 13,
    name: "subscriptionEndDate",
    type: "date",
    value: formData.subscriptionEndDate,
    label: "Subscription End Date",
    placeHolder: "",
    icon:  Calendar ,
  },
  {
    id: 14,
    name: "discount",
    type: "number",
    value: formData.discount,
    label: "Discount %",
    placeHolder: "",
    icon:  Percent ,
  },
];